# Generated by Django 5.0.2 on 2024-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_course_id_enrolledin_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
