# Generated by Django 5.0.2 on 2024-03-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_term_alter_course_code_alter_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrolledIn',
            new_name='Participates',
        ),
        migrations.RenameField(
            model_name='participates',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='participates',
            table='participates',
        ),
    ]
