# Generated by Django 5.0.2 on 2024-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_file_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='recording',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
