# Generated by Django 5.0.2 on 2024-03-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='forum',
        ),
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
