# Generated by Django 5.0.2 on 2024-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_post_forum_remove_tag_forum_post_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Help', max_length=30),
            preserve_default=False,
        ),
    ]
