# Generated by Django 5.0.2 on 2024-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_url'),
        ('api', '0011_post_title'),
    ]

    operations = [
    ]
