# Generated by Django 5.0.2 on 2024-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_topic_recording'),
        ('api', '0012_merge_0011_alter_course_url_0011_post_title'),
    ]

    operations = [
    ]
