# Generated by Django 5.0.2 on 2024-04-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_question_answer_quiz_question_quiz_quizresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
