# Generated by Django 5.0.2 on 2024-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
