# Generated by Django 5.0.2 on 2024-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_submission_feedback_alter_submission_grade'),
        ('api', '0019_alter_questionresponse_answer'),
    ]

    operations = [
    ]
