# Generated by Django 5.0.2 on 2024-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_commentimage_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
