# Generated by Django 5.0.2 on 2024-04-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimage',
            name='post',
        ),
        migrations.AddField(
            model_name='commentimage',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
            preserve_default=False,
        ),
    ]
